"""
Session-level unit tests for the BIWT walkthrough pipeline.

These tests exercise pure-Python session logic without any Qt/GUI.
Each test builds a WalkthroughSession, drives it through a sequence of
session-method calls that mirror what the step windows do, and asserts
on the resulting state — especially the coordinates DataFrame.

Fixtures list:
- nonspatial.csv
- spatial.csv
- spot_deconv.csv
- test_AnnData.h5ad
    AnnData object encoding version 0.1.0 (committed blob)
- toy_seurat.rds
    Tiny (10-cell) Seurat object generated by tests/fixtures/make_fixtures.R.
    Not committed — CI regenerates it on every run so it matches whatever
    R/Bioconductor versions conda resolved. Run the script locally (inside an
    env with Seurat) before running the R import test, or it will skip on the
    missing file.

Run with:
    cd biwt && pytest tests/ -v
"""
from __future__ import annotations

import dataclasses
import os
import sys
from pathlib import Path

import numpy as np
import pytest

from types import SimpleNamespace

from biwt.core import data_loader
from biwt.core.data_loader import (
    FormatSupport,
    supported_formats,
    DOCS_BASE_URL,
    INSTALL_DOCS_URL,
    TROUBLESHOOTING_DOCS_URL,
    LoadError,
    _extract_visium_microns_per_pixel,
)
from biwt.core.domain import classify_domain_mismatch, infer_domain
from biwt.core.positioning import build_ic_dataframe
from biwt.gui.walkthrough import WalkthroughSession, _step_predicates, _scale_domain
from biwt.types import BiwtInput, DomainSource, DomainSpec
from helpers import DOMAIN, FIXTURES, session_through_rename

# ---------------------------------------------------------------------------
# Fixture paths
# ---------------------------------------------------------------------------

SPATIAL_CSV     = str(FIXTURES / "spatial.csv")
NONSPATIAL_CSV  = str(FIXTURES / "nonspatial.csv")
SPOT_DECONV_CSV = str(FIXTURES / "spot_deconv.csv")
PIXEL_CSV       = str(FIXTURES / "spatial_pixels.csv")
SEURAT_RDS = str(FIXTURES / "toy_seurat.rds")
ANN_DATA = str(FIXTURES / "test_AnnData.h5ad")

# Cells in the toy Seurat fixture (see tests/fixtures/make_fixtures.R).
TOY_N_CELLS = 10



def _session(csv_path: str) -> WalkthroughSession:
    """Load a CSV and return a fresh WalkthroughSession with data attached."""
    data = data_loader.load(csv_path)
    s = WalkthroughSession(biwt_input=BiwtInput(preferred_domain=DOMAIN))
    s.data = data
    return s


# ---------------------------------------------------------------------------
# Data loader basics
# ---------------------------------------------------------------------------

class TestDataLoader:
    def test_spatial_csv_has_spatial(self):
        data = data_loader.load(SPATIAL_CSV)
        assert data.has_spatial
        assert data.n_cells == 7
        assert "type" in data.obs.columns

    def test_nonspatial_csv_no_spatial(self):
        data = data_loader.load(NONSPATIAL_CSV)
        assert not data.has_spatial
        assert data.n_cells == 6

    def test_spot_deconv_csv_has_prob_columns(self):
        data = data_loader.load(SPOT_DECONV_CSV)
        assert data.has_spatial
        assert len(data.probability_columns) == 3
        assert all(c.endswith("_probability") for c in data.probability_columns)

    def test_load_seurat(self):
        pytest.importorskip("rpy2")
        pytest.importorskip("anndata2ri")
        if not os.path.exists(SEURAT_RDS):
            pytest.skip("run tests/fixtures/make_fixtures.R to generate the toy Seurat fixture")
        data = data_loader.load(SEURAT_RDS)
        assert data.n_cells == TOY_N_CELLS
        assert not data.has_spatial

    def test_load_ann_data(self):
        data = data_loader.load(ANN_DATA)
        assert data.n_cells == 3180
        # This AnnData carries Visium-style imagerow/imagecol columns, now
        # recognized as spatial coordinates (last-resort fallback).
        assert data.has_spatial

    def test_pixel_csv_has_spatial(self):
        data = data_loader.load(PIXEL_CSV)
        assert data.has_spatial
        assert data.n_cells == 5

    def test_pixel_csv_spatial_location_names_columns(self):
        data = data_loader.load(PIXEL_CSV)
        assert "imagecol" in data.spatial_location
        assert "imagerow" in data.spatial_location
        assert "image columns" in data.spatial_location.lower()

    def test_pixel_csv_no_file_factor(self):
        # A bare imagerow/imagecol CSV carries no scale factor.
        data = data_loader.load(PIXEL_CSV)
        assert data.host_units_per_data_unit is None


# ---------------------------------------------------------------------------
# LoadError docs pointer
#
# Only failures a user fixes by changing their environment carry docs_url;
# failures about the file itself must not, or every bad CSV would send the
# user to the R setup guide.
# ---------------------------------------------------------------------------

class TestLoadErrorDocsPointer:
    def test_bare_load_error_has_no_docs_url(self):
        assert LoadError("something went wrong").docs_url is None

    def test_unsupported_extension_has_no_docs_url(self):
        with pytest.raises(LoadError) as exc:
            data_loader.load("sample.txt")
        assert exc.value.docs_url is None

    def test_unreadable_csv_has_no_docs_url(self):
        with pytest.raises(LoadError) as exc:
            data_loader.load(str(FIXTURES / "does_not_exist.csv"))
        assert exc.value.docs_url is None

    def test_missing_anndata_points_at_install_docs(self, monkeypatch):
        # Setting a module to None in sys.modules makes `import` raise ImportError.
        monkeypatch.setitem(sys.modules, "anndata", None)
        with pytest.raises(LoadError) as exc:
            data_loader.load("sample.h5ad")
        assert exc.value.docs_url == INSTALL_DOCS_URL
        assert "biwt[anndata]" in str(exc.value)

    @pytest.mark.parametrize("suffix", [".rds", ".rda", ".rdata"])
    def test_missing_rpy2_stack_points_at_install_docs(self, monkeypatch, suffix):
        monkeypatch.setitem(sys.modules, "anndata2ri", None)
        with pytest.raises(LoadError) as exc:
            data_loader.load(f"sample{suffix}")
        assert exc.value.docs_url == INSTALL_DOCS_URL
        assert "biwt[seurat]" in str(exc.value)

    @pytest.mark.parametrize("url", [INSTALL_DOCS_URL, TROUBLESHOOTING_DOCS_URL])
    def test_docs_urls_resolve_to_a_page_in_the_repo(self, url):
        # Guards the in-app links against a docs page being renamed or moved:
        # the published Pages path maps 1:1 onto a source file under docs/.
        repo_root = Path(__file__).resolve().parents[1]
        rel = url.removeprefix(DOCS_BASE_URL).strip("/")
        assert (repo_root / "docs" / f"{rel}.md").is_file(), \
            f"{url} does not correspond to docs/{rel}.md"

    def test_docs_base_url_matches_pyproject(self):
        # The PyPI "Documentation" link and the in-app links must not drift apart.
        try:
            import tomllib
        except ModuleNotFoundError:      # Python 3.9 / 3.10
            import tomli as tomllib
        repo_root = Path(__file__).resolve().parents[1]
        with open(repo_root / "pyproject.toml", "rb") as f:
            urls = tomllib.load(f)["project"]["urls"]
        assert urls["Documentation"] == DOCS_BASE_URL


# ---------------------------------------------------------------------------
# DomainSpec basics
# ---------------------------------------------------------------------------

class TestDomainSpec:
    def test_units_field_default(self):
        d = DomainSpec(xmin=0, xmax=1, ymin=0, ymax=1)
        assert d.units == "micron"

    def test_units_field_custom(self):
        d = DomainSpec(xmin=0, xmax=1, ymin=0, ymax=1, units="pixel")
        assert d.units == "pixel"

    def test_z_defaults(self):
        d = DomainSpec(xmin=0, xmax=1, ymin=0, ymax=1)
        assert d.zmin == -10.0
        assert d.zmax == 10.0

    def test_width_height(self):
        d = DomainSpec(xmin=-500, xmax=500, ymin=-250, ymax=250)
        assert d.width == 1000.0
        assert d.height == 500.0


# ---------------------------------------------------------------------------
# classify_domain_mismatch
# ---------------------------------------------------------------------------

class TestDomainMismatchClassification:
    PREFERRED = DomainSpec(xmin=-500, xmax=500, ymin=-500, ymax=500)

    def test_identical_returns_none(self):
        data = DomainSpec(xmin=-500, xmax=500, ymin=-500, ymax=500)
        assert classify_domain_mismatch(data, self.PREFERRED) is None

    def test_data_outside_x_returns_outside(self):
        data = DomainSpec(xmin=-500, xmax=600, ymin=-500, ymax=500)
        assert classify_domain_mismatch(data, self.PREFERRED) == "outside"

    def test_data_outside_y_returns_outside(self):
        data = DomainSpec(xmin=-500, xmax=500, ymin=-600, ymax=500)
        assert classify_domain_mismatch(data, self.PREFERRED) == "outside"

    def test_snug_fit_returns_none(self):
        # Data fills exactly 100% of preferred → no issue
        data = DomainSpec(xmin=-500, xmax=500, ymin=-500, ymax=500)
        assert classify_domain_mismatch(data, self.PREFERRED) is None

    def test_data_x_dim_below_half_returns_small(self):
        # width = 400 (40% of 1000) → small
        data = DomainSpec(xmin=-200, xmax=200, ymin=-500, ymax=500)
        assert classify_domain_mismatch(data, self.PREFERRED) == "small"

    def test_data_area_below_half_returns_small(self):
        # width=600 (60%), height=600 (60%), area=36% → small
        data = DomainSpec(xmin=-300, xmax=300, ymin=-300, ymax=300)
        assert classify_domain_mismatch(data, self.PREFERRED) == "small"

    def test_data_at_exactly_50pct_each_axis_returns_none(self):
        # width=500 (50%), height=500 (50%), area=25% → small (area check)
        data = DomainSpec(xmin=-250, xmax=250, ymin=-250, ymax=250)
        assert classify_domain_mismatch(data, self.PREFERRED) == "small"

    def test_data_covers_more_than_50pct_returns_none(self):
        # width=700 (70%), height=700 (70%), area=49% — below 50% area threshold
        data = DomainSpec(xmin=-350, xmax=350, ymin=-350, ymax=350)
        assert classify_domain_mismatch(data, self.PREFERRED) == "small"

    def test_data_covers_sufficient_area_returns_none(self):
        # width=800 (80%), height=800 (80%), area=64% → none
        data = DomainSpec(xmin=-400, xmax=400, ymin=-400, ymax=400)
        assert classify_domain_mismatch(data, self.PREFERRED) is None


# ---------------------------------------------------------------------------
# Session domain overrides
# ---------------------------------------------------------------------------

class TestEffectiveDomain:
    def test_effective_domain_defaults_to_preferred(self):
        s = _session(SPATIAL_CSV)
        assert s.effective_domain is s.preferred_domain

    def test_user_domain_overrides_the_host_domain(self):
        s = _session(SPATIAL_CSV)
        user = DomainSpec(xmin=-999, xmax=999, ymin=-999, ymax=999, source=DomainSource.USER)
        s.user_domain = user
        assert s.effective_domain is user

    def test_there_is_no_third_domain_between_host_and_user(self):
        """The split-brain guard, asserted on the session rather than the widget.

        ``effective_domain`` used to consult a latched ``inferred_domain`` copy of
        the host's box while ``preferred_domain`` read the host's live one, so a
        host that refreshed its input made the two disagree — and one dialog reads
        both. Removing the field is what makes them the same object; this pins it,
        since a dataclass will happily accept the attribute again.
        """
        s = _session(SPATIAL_CSV)
        assert not hasattr(s, "inferred_domain")
        assert s.effective_domain is s.preferred_domain

    def test_scale_defaults(self):
        # No factor by default → placement scale is identity (1.0), apply on.
        s = _session(SPATIAL_CSV)
        assert s.scale_factor is None
        assert s.apply_scale is True
        assert s.effective_scale() == 1.0

    def test_effective_scale_truth_table(self):
        s = _session(SPATIAL_CSV)
        s.scale_factor = 0.5
        assert s.effective_scale() == 0.5          # factor + apply on
        s.apply_scale = False
        assert s.effective_scale() == 1.0          # apply off → identity
        s.apply_scale = True
        s.scale_factor = None
        assert s.effective_scale() == 1.0          # no factor → identity

    def test_domain_accepted_default_false(self):
        s = _session(SPATIAL_CSV)
        assert s.domain_accepted is False

    def test_data_domain_default_none(self):
        s = _session(SPATIAL_CSV)
        assert s.data_domain is None


# ---------------------------------------------------------------------------
# Cluster column / collect_cell_type_data
# ---------------------------------------------------------------------------

class TestCollectCellTypeData:
    def test_extracts_unique_types_sorted(self):
        s = _session(SPATIAL_CSV)
        s.current_column = "type"
        s.collect_cell_type_data()
        assert s.cell_types_list_original == ["Macrophage", "T_cell", "Tumor"]
        assert len(s.cell_types_original) == 7

    def test_per_cell_labels_match_obs(self):
        s = _session(SPATIAL_CSV)
        s.current_column = "type"
        s.collect_cell_type_data()
        assert s.cell_types_original == list(s.data.obs["type"])


# ---------------------------------------------------------------------------
# Spatial setup
# ---------------------------------------------------------------------------

class TestSetupSpatialData:
    def test_spatial_csv_sets_array(self):
        s = _session(SPATIAL_CSV)
        s.setup_spatial_data()
        assert s.spatial_data is not None
        assert s.spatial_data.shape == (7, 3)  # x, y, z(=0)

    def test_nonspatial_csv_leaves_none(self):
        s = _session(NONSPATIAL_CSV)
        s.setup_spatial_data()
        assert s.spatial_data is None

    def test_pixel_csv_maps_and_flips_axes(self):
        # Fixture (imagecol, imagerow): (10,0) (20,10) (30,20) (40,30) (50,40).
        # imagecol -> x directly; imagerow -> y flipped (y = rowmax - row).
        s = _session(PIXEL_CSV)
        s.setup_spatial_data()
        assert s.spatial_data.shape == (5, 3)
        np.testing.assert_allclose(s.spatial_data[:, 0], [10, 20, 30, 40, 50])
        np.testing.assert_allclose(s.spatial_data[:, 1], [40, 30, 20, 10, 0])
        np.testing.assert_allclose(s.spatial_data[:, 2], 0.0)


class TestPixelDataDomain:
    def test_image_columns_recognized_and_flipped(self):
        # imagerow/imagecol still recognized + y-flipped, but NOT labeled "pixel":
        # x = imagecol (10..50), y = flipped imagerow (0..40); units = "data unit".
        data = data_loader.load(PIXEL_CSV)
        d = infer_domain(obs=data.obs, obsm=data.obsm)
        assert d.units == "data unit"
        assert (d.xmin, d.xmax) == (10, 50)
        assert (d.ymin, d.ymax) == (0, 40)

    def test_standard_csv_domain_units_data_units(self):
        # BIWT infers no unit name from the data.
        data = data_loader.load(SPATIAL_CSV)
        d = infer_domain(obs=data.obs, obsm=data.obsm)
        assert d.units == "data unit"


class TestScaleFactor:
    def test_extract_visium_factor(self):
        # 55 µm spot / 110 px diameter → 0.5 µm/pixel.
        ad = SimpleNamespace(uns={
            "spatial": {"lib1": {"scalefactors": {"spot_diameter_fullres": 110.0}}}
        })
        assert _extract_visium_microns_per_pixel(ad) == 0.5

    def test_extract_visium_factor_missing(self):
        assert _extract_visium_microns_per_pixel(SimpleNamespace(uns={})) is None

    def test_extract_visium_factor_nonpositive(self):
        ad = SimpleNamespace(uns={
            "spatial": {"lib1": {"scalefactors": {"spot_diameter_fullres": 0}}}
        })
        assert _extract_visium_microns_per_pixel(ad) is None

    def test_scale_domain_xy_only(self):
        d = DomainSpec(xmin=0, xmax=100, ymin=0, ymax=200, zmin=-10, zmax=10)
        scaled = _scale_domain(d, 0.5)
        assert (scaled.xmin, scaled.xmax) == (0.0, 50.0)
        assert (scaled.ymin, scaled.ymax) == (0.0, 100.0)
        assert (scaled.zmin, scaled.zmax) == (-10, 10)   # z untouched
        assert scaled.units == "micron"


# ---------------------------------------------------------------------------
# compute_intermediate_types (edit cell types step)
# ---------------------------------------------------------------------------

class TestComputeIntermediateTypes:
    def _base_session(self):
        s = _session(NONSPATIAL_CSV)
        s.current_column = "type"
        s.collect_cell_type_data()
        return s

    def test_all_kept(self):
        s = self._base_session()
        s.cell_type_dict_on_edit = {ct: ct for ct in s.cell_types_list_original}
        s.compute_intermediate_types()
        assert set(s.intermediate_types) == {"Macrophage", "T_cell", "Tumor"}
        assert all(len(v) == 1 for v in s.intermediate_type_pre_image.values())

    def test_delete_one(self):
        s = self._base_session()
        s.cell_type_dict_on_edit = {
            "Macrophage": "Macrophage",
            "T_cell": "T_cell",
            "Tumor": None,  # deleted
        }
        s.compute_intermediate_types()
        assert "Tumor" not in s.intermediate_types
        assert set(s.intermediate_types) == {"Macrophage", "T_cell"}

    def test_merge_two(self):
        s = self._base_session()
        # Merge Tumor into T_cell (T_cell is the first / target)
        s.cell_type_dict_on_edit = {
            "Macrophage": "Macrophage",
            "T_cell": "T_cell",
            "Tumor": "T_cell",   # merged
        }
        s.compute_intermediate_types()
        assert set(s.intermediate_types) == {"Macrophage", "T_cell"}
        assert sorted(s.intermediate_type_pre_image["T_cell"]) == ["T_cell", "Tumor"]

    def test_delete_all_except_one(self):
        s = self._base_session()
        s.cell_type_dict_on_edit = {
            "Macrophage": None,
            "T_cell": "T_cell",
            "Tumor": None,
        }
        s.compute_intermediate_types()
        assert s.intermediate_types == ["T_cell"]


# ---------------------------------------------------------------------------
# apply_rename — non-spatial path
# ---------------------------------------------------------------------------

class TestApplyRenameNonSpatial:
    def _setup(self, cell_type_dict_on_edit=None, intermediate_to_final=None):
        """
        Mirror what RenameCellTypesWindow.process_window() does:
        - cell_type_dict_on_edit: original → intermediate | None
        - intermediate_to_final: intermediate name → final (renamed) name
          Defaults to identity.  cell_type_dict_on_rename and
          cell_types_list_final are derived from this, including ALL
          original names that folded into each intermediate (merged types).
        """
        s = _session(NONSPATIAL_CSV)
        s.current_column = "type"
        s.collect_cell_type_data()
        s.spatial_query_answer = False
        s.cell_type_dict_on_edit = cell_type_dict_on_edit or {
            ct: ct for ct in s.cell_types_list_original
        }
        s.compute_intermediate_types()

        if intermediate_to_final is None:
            intermediate_to_final = {ct: ct for ct in s.intermediate_types}

        # cell_types_list_final = the renamed names (values of the mapping)
        s.cell_types_list_final = list(intermediate_to_final.values())
        # cell_type_dict_on_rename maps every ORIGINAL name to its final name,
        # expanding merged groups via intermediate_type_pre_image.
        s.cell_type_dict_on_rename = {}
        for intermed, final in intermediate_to_final.items():
            for orig in s.intermediate_type_pre_image.get(intermed, [intermed]):
                s.cell_type_dict_on_rename[orig] = final

        s.apply_rename()
        return s

    def test_counts_match_fixture(self):
        s = self._setup()
        assert s.cell_counts == {"Macrophage": 1, "T_cell": 3, "Tumor": 2}

    def test_rename_changes_label(self):
        s = self._setup(intermediate_to_final={
            "Macrophage": "MΦ", "T_cell": "T_cell", "Tumor": "Tumor",
        })
        assert "MΦ" in s.cell_counts
        assert "Macrophage" not in s.cell_counts
        assert s.cell_counts["MΦ"] == 1

    def test_delete_removes_from_counts(self):
        s = self._setup(
            cell_type_dict_on_edit={
                "Macrophage": None,
                "T_cell": "T_cell",
                "Tumor": "Tumor",
            },
        )
        assert "Macrophage" not in s.cell_counts
        assert s.cell_counts["T_cell"] == 3

    def test_merge_sums_counts(self):
        # Tumor merged into T_cell → intermediate_types = ["Macrophage", "T_cell"]
        s = self._setup(
            cell_type_dict_on_edit={
                "Macrophage": "Macrophage",
                "T_cell": "T_cell",
                "Tumor": "T_cell",
            },
            # No rename; intermediate names kept as-is
        )
        assert s.cell_counts["T_cell"] == 5  # 3 T_cell + 2 Tumor


# ---------------------------------------------------------------------------
# apply_rename — spatial path
# ---------------------------------------------------------------------------

class TestApplyRenameSpatial:
    def _setup(self):
        s = _session(SPATIAL_CSV)
        s.current_column = "type"
        s.collect_cell_type_data()
        s.spatial_query_answer = True
        s.setup_spatial_data()
        s.cell_type_dict_on_edit = {ct: ct for ct in s.cell_types_list_original}
        s.compute_intermediate_types()
        s.cell_types_list_final = list(s.intermediate_types)
        s.cell_type_dict_on_rename = {ct: ct for ct in s.intermediate_types}
        s.apply_rename()
        return s

    def test_spatial_data_final_shape(self):
        s = self._setup()
        assert s.spatial_data_final is not None
        assert s.spatial_data_final.shape[0] == s.data.n_cells
        assert s.spatial_data_final.shape[1] == 3

    def test_counts_match_fixture(self):
        s = self._setup()
        assert s.cell_counts == {"Macrophage": 2, "T_cell": 2, "Tumor": 3}

    def test_cell_types_final_length_matches_spatial(self):
        s = self._setup()
        assert len(s.cell_types_final) == s.spatial_data_final.shape[0]


# ---------------------------------------------------------------------------
# Spot deconvolution session setup
# ---------------------------------------------------------------------------

class TestSpotDeconvolution:
    def test_setup_extracts_cell_type_list(self):
        s = _session(SPOT_DECONV_CSV)
        s.perform_spot_deconvolution = True
        s.setup_spot_deconvolution_data()
        assert set(s.cell_types_list_original) == {"T_cell", "Tumor", "Macrophage"}

    def test_cell_types_max_length(self):
        s = _session(SPOT_DECONV_CSV)
        s.perform_spot_deconvolution = True
        s.setup_spot_deconvolution_data()
        assert len(s.cell_types_max) == 6

    def test_max_type_is_highest_prob(self):
        """First row: T_cell=0.8 → should be T_cell."""
        s = _session(SPOT_DECONV_CSV)
        s.perform_spot_deconvolution = True
        s.setup_spot_deconvolution_data()
        assert s.cell_types_max[0] == "T_cell"
        assert s.cell_types_max[2] == "Tumor"
        assert s.cell_types_max[4] == "Macrophage"


# ---------------------------------------------------------------------------
# Full pipeline → output DataFrame
# ---------------------------------------------------------------------------

class TestFullPipelineNonSpatial:
    """Drive the complete session sequence and inspect the final DataFrame."""

    def test_coordinates_dataframe_columns(self):
        s = _session(NONSPATIAL_CSV)
        session_through_rename(s)

        # Simulate cell-count override (user keeps defaults)
        # coords_by_type is set by PositionsWindow — simulate minimal placement
        import numpy as np
        rng = np.random.default_rng(42)
        for ct, count in s.cell_counts.items():
            s.coords_by_type[ct] = np.column_stack([
                rng.uniform(-500, 500, count),
                rng.uniform(-500, 500, count),
                np.zeros(count),
            ])

        df = build_ic_dataframe(s.coords_by_type)
        assert list(df.columns) == ["x", "y", "z", "type"]
        assert len(df) == 6
        assert set(df["type"].unique()) == {"Macrophage", "T_cell", "Tumor"}

    def test_delete_reduces_row_count(self):
        s = _session(NONSPATIAL_CSV)
        s.current_column = "type"
        s.collect_cell_type_data()
        s.spatial_query_answer = False
        s.cell_type_dict_on_edit = {
            "Macrophage": None,
            "T_cell": "T_cell",
            "Tumor": "Tumor",
        }
        s.compute_intermediate_types()
        s.cell_types_list_final = list(s.intermediate_types)
        s.cell_type_dict_on_rename = {ct: ct for ct in s.intermediate_types}
        s.apply_rename()

        import numpy as np
        rng = np.random.default_rng(0)
        for ct, count in s.cell_counts.items():
            s.coords_by_type[ct] = np.column_stack([
                rng.uniform(-500, 500, count),
                rng.uniform(-500, 500, count),
                np.zeros(count),
            ])

        df = build_ic_dataframe(s.coords_by_type)
        assert "Macrophage" not in df["type"].values
        assert len(df) == 5  # 3 T_cell + 2 Tumor


class TestFullPipelineSpatial:
    def test_coordinates_come_from_data(self):
        s = _session(SPATIAL_CSV)
        s.current_column = "type"
        s.collect_cell_type_data()
        s.spatial_query_answer = True
        s.setup_spatial_data()
        s.cell_type_dict_on_edit = {ct: ct for ct in s.cell_types_list_original}
        s.compute_intermediate_types()
        s.cell_types_list_final = list(s.intermediate_types)
        s.cell_type_dict_on_rename = {ct: ct for ct in s.intermediate_types}
        s.apply_rename()

        # Populate coords_by_type from spatial_data_final
        for ct in s.cell_types_list_final:
            mask = np.array(s.cell_types_final) == ct
            s.coords_by_type[ct] = s.spatial_data_final[mask]

        df = build_ic_dataframe(s.coords_by_type)
        assert len(df) == 7
        # x/y coords should match the fixture values
        t_cell_rows = df[df["type"] == "T_cell"]
        assert set(t_cell_rows["x"].tolist()) == {100, 150}


# ---------------------------------------------------------------------------
# Step sequencing — pure-Python predicate mirror of _build_next_window
# ---------------------------------------------------------------------------

def _next_step(s: WalkthroughSession) -> "str | None":
    """Return the label of the first pending step for session *s*, or None.

    Delegates directly to ``_step_predicates`` from ``walkthrough.py`` so
    this helper stays in sync with the real step-selection logic automatically.
    Reseeds first, exactly as ``_build_next_window`` does, since predicates
    read state that ``reseed_derived_state`` owns.
    """
    s.reseed_derived_state()
    for predicate, label in _step_predicates(s):
        if predicate():
            return label
    return None


class TestStepSequencing:
    """Verify _next_step returns the correct step label for each partial session state."""

    def test_fresh_spot_deconv_csv_goes_to_spot_deconv_query(self):
        # spatial CSV with probability columns → SpotDeconvQuery (has_spatial + prob cols)
        s = _session(SPOT_DECONV_CSV)
        # spot_deconv_asked is False by default, data has prob cols and spatial
        assert _next_step(s) == "SpotDeconvQuery"

    def test_fresh_spatial_csv_no_prob_cols_goes_to_cluster_column(self):
        # spatial CSV without probability columns — no spot-deconv query, skip to
        # ClusterColumn (current_column is None)
        s = _session(SPATIAL_CSV)
        assert not s.data.probability_columns  # no prob cols in spatial.csv
        assert _next_step(s) == "ClusterColumn"

    def test_after_spot_deconv_declined_goes_to_cluster_column(self):
        # spot_deconv_asked=True, perform_spot_deconvolution=False, current_column=None
        s = _session(SPOT_DECONV_CSV)
        s.spot_deconv_asked = True
        s.perform_spot_deconvolution = False
        assert s.current_column is None
        assert _next_step(s) == "ClusterColumn"

    def test_after_column_set_with_spatial_data_goes_to_spatial_query(self):
        # current_column set, question unanswered, data has spatial
        s = _session(SPATIAL_CSV)
        s.current_column = "type"
        s.collect_cell_type_data()
        # spatial_query_answer is None and data.has_spatial → SpatialQuery
        assert s.spatial_query_answer is None
        assert s.data.has_spatial
        assert _next_step(s) == "SpatialQuery"

    def test_after_use_spatial_false_cell_counts_not_confirmed_goes_to_cell_counts(self):
        # spatial declined, cell_type_dict_on_edit set, cell_types_list_final set,
        # cell_counts_confirmed=False → CellCounts
        s = _session(NONSPATIAL_CSV)
        session_through_rename(s)
        # cell_counts_confirmed defaults to False
        assert not s.cell_counts_confirmed
        assert _next_step(s) == "CellCounts"

    def test_after_use_spatial_true_skips_cell_counts_goes_to_positions(self):
        # spatial accepted → CellCounts predicate (not use_spatial_data) is False
        # positions_set=False → Positions
        s = _session(SPATIAL_CSV)
        s.current_column = "type"
        s.collect_cell_type_data()
        s.spatial_query_answer = True
        s.setup_spatial_data()
        s.cell_type_dict_on_edit = {ct: ct for ct in s.cell_types_list_original}
        s.compute_intermediate_types()
        s.cell_types_list_final = list(s.intermediate_types)
        s.cell_type_dict_on_rename = {ct: ct for ct in s.intermediate_types}
        s.apply_rename()
        # cell_counts_confirmed is False but use_spatial_data is True → CellCounts skipped
        assert s.use_spatial_data is True
        assert not s.positions_set
        assert _next_step(s) == "Positions"

    def test_after_positions_set_and_parameters_not_loaded_goes_to_load_parameters(self):
        s = _session(NONSPATIAL_CSV)
        session_through_rename(s)
        s.cell_counts_confirmed = True
        s.positions_set = True
        assert not s.parameters_loaded
        assert _next_step(s) == "LoadCellParameters"

    def test_all_flags_done_returns_none(self):
        # All predicates False → workflow complete → None
        s = _session(NONSPATIAL_CSV)
        session_through_rename(s)
        s.cell_counts_confirmed = True
        s.positions_set = True
        s.parameters_loaded = True
        assert _next_step(s) is None


# ---------------------------------------------------------------------------
# Full spot-deconv pipeline → output DataFrame
# ---------------------------------------------------------------------------

class TestSpotDeconvFullPipeline:
    """Drive a WalkthroughSession from spot_deconv.csv to build_ic_dataframe."""

    def _setup_session(self) -> "WalkthroughSession":
        """Replicate all steps up to (but not including) PositionsWindow."""
        s = _session(SPOT_DECONV_CSV)

        # The deconvolution query window writes only this flag; everything it
        # implies — the probability-derived cell types, the per-spot dicts and
        # the coordinates — is derived by reseed_derived_state().
        s.perform_spot_deconvolution = True
        s.reseed_derived_state()

        # No cluster column is chosen on this path, and cell_types_original
        # stays None: every downstream reader branches on
        # perform_spot_deconvolution and uses cell_types_max instead.
        return s

    def test_setup_produces_three_cell_types(self):
        s = self._setup_session()
        assert set(s.cell_types_list_original) == {"T_cell", "Tumor", "Macrophage"}

    def test_setup_spot_deconv_populates_prob_dicts(self):
        s = self._setup_session()
        assert s.cell_prob_feature_dicts is not None
        assert len(s.cell_prob_feature_dicts) == 6

    def test_setup_spatial_data_shape(self):
        s = self._setup_session()
        assert s.spatial_data is not None
        assert s.spatial_data.shape == (6, 3)

    def test_collect_via_spot_deconv_path_cell_types_max(self):
        """cell_types_max has one entry per spot, labeled by max-probability type."""
        s = self._setup_session()
        # First two spots are T_cell (prob 0.8 and 0.7), next two Tumor, last two Macrophage
        assert s.cell_types_max[0] == "T_cell"
        assert s.cell_types_max[1] == "T_cell"
        assert s.cell_types_max[2] == "Tumor"
        assert s.cell_types_max[3] == "Tumor"
        assert s.cell_types_max[4] == "Macrophage"
        assert s.cell_types_max[5] == "Macrophage"

    def test_compute_intermediate_types_all_kept(self):
        s = self._setup_session()
        s.cell_type_dict_on_edit = {ct: ct for ct in s.cell_types_list_original}
        s.compute_intermediate_types()
        assert set(s.intermediate_types) == {"T_cell", "Tumor", "Macrophage"}

    def test_apply_rename_identity_produces_correct_final_types(self):
        s = self._setup_session()
        s.cell_type_dict_on_edit = {ct: ct for ct in s.cell_types_list_original}
        s.compute_intermediate_types()
        # Identity rename
        s.cell_types_list_final = list(s.intermediate_types)
        s.cell_type_dict_on_rename = {ct: ct for ct in s.cell_types_list_original}
        s.apply_rename()
        # In the spot-deconv path, cell_types_final is sorted(final_set)
        assert set(s.cell_types_final) == {"T_cell", "Tumor", "Macrophage"}
        # spatial_data_final should have one row per retained spot
        assert s.spatial_data_final is not None
        assert s.spatial_data_final.shape[0] == 6

    def test_build_ic_dataframe_has_6_rows_and_all_three_types(self):
        """Full pipeline: load → spot deconv setup → rename identity → build DataFrame."""
        s = self._setup_session()
        s.cell_type_dict_on_edit = {ct: ct for ct in s.cell_types_list_original}
        s.compute_intermediate_types()
        s.cell_types_list_final = list(s.intermediate_types)
        s.cell_type_dict_on_rename = {ct: ct for ct in s.cell_types_list_original}
        s.apply_rename()

        # Populate coords_by_type from spatial_data_final, grouped by cell_types_final.
        # In the spot-deconv case cell_types_final is a sorted list (not per-cell),
        # so we group by using the per-spot probability dicts and the spatial rows.
        # Mirror what PositionsWindow does: one coordinate per retained spot, assigned
        # to the dominant (max-prob) type derived from cell_types_max.
        for i, (sp, prob_dict) in enumerate(
            zip(s.spatial_data_final, s.cell_prob_feature_dicts_final)
        ):
            # dominant type for this spot = argmax of the (already renamed) prob dict
            dominant = max(prob_dict, key=lambda k: prob_dict[k])
            if dominant not in s.coords_by_type:
                s.coords_by_type[dominant] = []
            s.coords_by_type[dominant].append(sp)

        # Convert lists → arrays
        for ct in s.coords_by_type:
            s.coords_by_type[ct] = np.vstack(s.coords_by_type[ct])

        df = build_ic_dataframe(s.coords_by_type)

        assert list(df.columns) == ["x", "y", "z", "type"]
        assert len(df) == 6
        assert set(df["type"].unique()) == {"T_cell", "Tumor", "Macrophage"}


# ---------------------------------------------------------------------------
# Zero cell counts
# ---------------------------------------------------------------------------

class TestZeroCellCounts:
    """A count of zero is allowed and means "define this type, place none of it".

    The type still reaches the output config as a ``<cell_definition>`` — cell
    definitions are driven by ``cell_types_list_final``, never by counts — but
    contributes no rows to the coordinates DataFrame. Deleting the type at the
    edit step is the way to remove it from the config entirely.
    """

    @staticmethod
    def _coords(n, seed=0):
        rng = np.random.default_rng(seed)
        return np.column_stack([
            rng.uniform(-500, 500, n),
            rng.uniform(-500, 500, n),
            np.zeros(n),
        ])

    def test_zero_count_type_contributes_no_rows(self):
        df = build_ic_dataframe({
            "Tumor": self._coords(3),
            "Ghost": np.empty((0, 3)),
            "T_cell": self._coords(2),
        })
        assert len(df) == 5
        assert set(df["type"].unique()) == {"Tumor", "T_cell"}
        assert "Ghost" not in set(df["type"])

    def test_other_types_are_unaffected_by_a_zero_neighbor(self):
        both = build_ic_dataframe({"Tumor": self._coords(3), "Ghost": np.empty((0, 3))})
        alone = build_ic_dataframe({"Tumor": self._coords(3)})
        assert both[["x", "y", "z"]].equals(alone[["x", "y", "z"]])

    def test_all_zero_counts_give_an_empty_frame(self):
        df = build_ic_dataframe({"Ghost": np.empty((0, 3)), "Phantom": np.empty((0, 3))})
        assert len(df) == 0
        assert list(df.columns) == ["x", "y", "z", "type"]

    def test_empty_frame_keeps_numeric_dtypes(self):
        """Object-dtype coordinate columns would propagate into a host's concat
        of these rows onto real ones."""
        empty = build_ic_dataframe({"Ghost": np.empty((0, 3))})
        populated = build_ic_dataframe({"Tumor": self._coords(2)})
        for col in ("x", "y", "z"):
            assert empty[col].dtype == populated[col].dtype == np.dtype("float64")

    def test_no_types_at_all_matches_the_all_empty_frame(self):
        assert list(build_ic_dataframe({}).dtypes) == list(
            build_ic_dataframe({"Ghost": np.empty((0, 3))}).dtypes
        )

    def test_zeroing_a_type_still_leaves_it_a_known_cell_type(self):
        """The acceptance criterion: absent from the coordinates, still a type the
        config must define. Contrast test_delete_removes_from_counts, where the
        type disappears from cell_counts entirely."""
        s = _session(NONSPATIAL_CSV)
        session_through_rename(s)

        s.cell_counts["Macrophage"] = 0          # what the counts screen now allows
        assert "Macrophage" in s.cell_types_list_final

        for ct, count in s.cell_counts.items():
            s.coords_by_type[ct] = self._coords(count, seed=1)

        df = build_ic_dataframe(s.coords_by_type)
        assert "Macrophage" not in set(df["type"])
        assert set(df["type"].unique()) == {"T_cell", "Tumor"}
        assert len(df) == sum(s.cell_counts.values())


# ---------------------------------------------------------------------------
# Spot-deconvolution apportionment
# ---------------------------------------------------------------------------

from biwt.core.positioning import apportion_spot_cells  # noqa: E402


class TestApportionSpotCells:
    """Equal-proportions apportionment with a shifted divisor.

    The shift means the first cell is contested like any other, so a type a
    deconvolution reports at ~1e-4 does not get a free cell in every spot.
    """

    def test_places_exactly_n_cells(self):
        for n in (1, 2, 3, 7, 50):
            got = apportion_spot_cells({"A": 0.5, "B": 0.3, "C": 0.2}, n)
            assert sum(got.values()) == n

    def test_keys_are_preserved_even_at_zero(self):
        got = apportion_spot_cells({"A": 0.9, "B": 0.1}, 1)
        assert set(got) == {"A", "B"}

    def test_non_positive_n_places_nothing(self):
        for n in (0, -3):
            assert apportion_spot_cells({"A": 1.0}, n) == {"A": 0}

    def test_no_types_is_not_an_error(self):
        assert apportion_spot_cells({}, 5) == {}

    def test_dominant_type_wins_the_first_cell(self):
        assert apportion_spot_cells({"A": 0.7, "B": 0.3}, 1) == {"A": 1, "B": 0}

    def test_trivial_probability_gets_no_cell_at_realistic_counts(self):
        """The whole point of the shifted divisor: no thin film of spurious cells."""
        for n in (1, 2, 3, 5, 10, 25):
            got = apportion_spot_cells({"A": 0.4, "B": 0.4, "C": 0.0001}, n)
            assert got["C"] == 0

    def test_a_leader_gets_its_second_cell_before_a_trivial_type_gets_its_first(self):
        got = apportion_spot_cells({"A": 0.7, "B": 0.2999, "C": 0.0001}, 3)
        assert got["A"] == 2 and got["C"] == 0

    def test_scale_invariant(self):
        """Probabilities need not sum to 1, so filtering to kept types is safe."""
        np.random.seed(0)
        a = apportion_spot_cells({"A": 0.6, "B": 0.3, "C": 0.1}, 9)
        np.random.seed(0)
        b = apportion_spot_cells({"A": 6.0, "B": 3.0, "C": 1.0}, 9)
        assert a == b

    def test_proportions_are_respected_at_larger_counts(self):
        got = apportion_spot_cells({"A": 0.5, "B": 0.3, "C": 0.2}, 100)
        assert got["A"] > got["B"] > got["C"]
        assert abs(got["A"] - 50) <= 2

    def test_ties_do_not_always_favour_the_first_listed_type(self):
        """The regression: max() broke ties by dict order, i.e. obs column order,
        so with balanced types the first-listed one collected the surplus in
        *every* spot — a tissue-wide skew rather than per-spot noise."""
        np.random.seed(1234)
        winners = [
            max(apportion_spot_cells({"A": 0.5, "B": 0.5}, 1).items(),
                key=lambda kv: kv[1])[0]
            for _ in range(400)
        ]
        assert set(winners) == {"A", "B"}
        # Roughly balanced rather than 400/0.
        assert 140 < winners.count("A") < 260

    def test_tie_break_order_does_not_matter(self):
        """Same mixture, different dict insertion order, same distribution."""
        np.random.seed(7)
        ab = sum(apportion_spot_cells({"A": 0.5, "B": 0.5}, 1)["A"] for _ in range(400))
        np.random.seed(7)
        ba = sum(apportion_spot_cells({"B": 0.5, "A": 0.5}, 1)["A"] for _ in range(400))
        assert 140 < ab < 260 and 140 < ba < 260


# ---------------------------------------------------------------------------
# Derived state — reseed_derived_state()
#
# _STEP_FIELDS covers what the user chose; everything derived from those choices
# is reseed's job. The invariant that matters: reseed repairs state a downstream
# invalidation wiped, and never overwrites a decision the user made.
# ---------------------------------------------------------------------------

class TestReseedDerivedState:
    def test_noop_without_data(self):
        s = WalkthroughSession(biwt_input=BiwtInput(preferred_domain=DOMAIN))
        s.reseed_derived_state()          # must not raise
        assert s.spatial_query_answer is None

    def test_non_spatial_data_needs_no_spatial_answer(self):
        # Nothing is derived here: the property reads False off the data itself,
        # so the unanswered question stays unanswered and harmless.
        s = _session(NONSPATIAL_CSV)
        s.reseed_derived_state()
        assert s.spatial_query_answer is None
        assert s.use_spatial_data is False

    def test_deconvolution_implies_spatial(self):
        s = _session(SPOT_DECONV_CSV)
        s.perform_spot_deconvolution = True
        s.reseed_derived_state()
        # The question is never asked, yet spatial is in use.
        assert s.spatial_query_answer is None
        assert s.use_spatial_data is True

    def test_deconvolution_rebuilds_all_three_probability_fields(self):
        s = _session(SPOT_DECONV_CSV)
        s.perform_spot_deconvolution = True
        s.reseed_derived_state()
        assert s.cell_types_list_original == ["Macrophage", "T_cell", "Tumor"]
        assert len(s.cell_types_max) == 6
        assert len(s.cell_prob_feature_dicts) == 6

    def test_deconvolution_rebuilds_after_a_partial_wipe(self):
        s = _session(SPOT_DECONV_CSV)
        s.perform_spot_deconvolution = True
        s.reseed_derived_state()
        # One field cleared is enough: a single function produces all three.
        s.cell_types_list_original = None
        s.reseed_derived_state()
        assert s.cell_types_list_original == ["Macrophage", "T_cell", "Tumor"]
        assert s.cell_prob_feature_dicts is not None

    def test_declining_deconvolution_clears_its_artifacts(self):
        s = _session(SPOT_DECONV_CSV)
        s.perform_spot_deconvolution = True
        s.reseed_derived_state()
        s.perform_spot_deconvolution = False
        s.reseed_derived_state()
        assert s.cell_types_max is None
        assert s.cell_prob_feature_dicts is None

    def test_spatial_coordinates_are_derived(self):
        s = _session(SPATIAL_CSV)
        assert s.spatial_data is None
        s.reseed_derived_state()
        assert s.spatial_data is not None
        assert s.spatial_data.shape[1] == 3

    def test_is_idempotent(self):
        s = _session(SPOT_DECONV_CSV)
        s.perform_spot_deconvolution = True
        s.reseed_derived_state()
        first = (
            list(s.cell_types_list_original),
            list(s.cell_types_max),
            [dict(d) for d in s.cell_prob_feature_dicts],
            s.spatial_data.copy(),
        )
        s.reseed_derived_state()
        assert s.cell_types_list_original == first[0]
        assert s.cell_types_max == first[1]
        assert [dict(d) for d in s.cell_prob_feature_dicts] == first[2]
        assert np.array_equal(s.spatial_data, first[3])

    def test_preserves_the_users_spatial_choice(self):
        # The one field reseed must keep its hands off: spatial data present,
        # no deconvolution, so the answer is the user's to give.
        s = _session(SPATIAL_CSV)
        s.spatial_query_answer = False
        s.reseed_derived_state()
        assert s.spatial_query_answer is False
        s.spatial_query_answer = True
        s.reseed_derived_state()
        assert s.spatial_query_answer is True

    def test_does_not_overwrite_the_chosen_column_or_its_cell_types(self):
        s = _session(SPATIAL_CSV)
        s.current_column = "type"
        s.collect_cell_type_data()
        before = list(s.cell_types_list_original)
        s.reseed_derived_state()
        assert s.current_column == "type"
        assert s.cell_types_list_original == before

    def test_deconvolution_is_unreachable_without_coordinates(self):
        # Guarded by the step predicate rather than repaired afterwards: the
        # window that sets the flag is only built for data that has coordinates.
        s = _session(NONSPATIAL_CSV)
        assert _next_step(s) != "SpotDeconvQuery"


class TestCollectCellTypeDataEdgeCases:
    """A missing column, and labels that are not strings.

    Named apart from ``TestCollectCellTypeData`` above rather than merged: same
    subject, but these are the failure modes. Sharing the name silently shadowed
    that class and dropped its two tests from the run — caught by pyflakes, not by
    the suite, which is the point of the static check.
    """

    def test_without_a_column_raises_a_named_error(self):
        s = _session(SPATIAL_CSV)
        with pytest.raises(ValueError, match="current_column"):
            s.collect_cell_type_data()

    def test_numeric_column_labels_are_stringified_per_cell(self):
        """A numeric cluster column must survive apply_rename.

        cell_types_list_original was always stringified but cell_types_original
        was not, so with integer Leiden/Louvain ids the rename mapping (keyed by
        the string labels) matched nothing and every cell was dropped.
        """
        s = _session(SPOT_DECONV_CSV)
        s.current_column = "Tumor_probability"        # a float column
        s.collect_cell_type_data()
        assert all(isinstance(ct, str) for ct in s.cell_types_original)
        assert set(s.cell_types_original) <= set(s.cell_types_list_original)

    def test_numeric_labels_survive_apply_rename(self):
        s = _session(SPOT_DECONV_CSV)
        session_through_rename(s, column="Tumor_probability")
        assert len(s.cell_types_final) == s.data.n_cells
        assert sum(s.cell_counts.values()) == s.data.n_cells


# ---------------------------------------------------------------------------
# API boundary — what the host is promised
# ---------------------------------------------------------------------------

class TestApiBoundary:
    def test_cell_templates_defaults_to_an_empty_mapping(self):
        from biwt.types import BiwtResult
        result = BiwtResult(
            coordinates=build_ic_dataframe({}),
            cell_type_map={},
            domain_used=DOMAIN,
        )
        assert result.cell_templates == {}

    def test_cell_definitions_xml_is_gone(self):
        # BIWT no longer assembles framework XML; the host owns that.
        from biwt.types import BiwtResult
        assert "cell_definitions_xml" not in {
            f.name for f in dataclasses.fields(BiwtResult)
        }

    def test_biwt_input_is_only_what_a_run_re_reads(self):
        """Widget setup is not host state, so it is not on the per-run value.

        The library was a field here, and had to be documented as read once at
        construction — which is the tell that it belongs to the widget: the user
        edits it, and a per-run re-read would undo that.
        """
        assert "cell_template_paths" not in {
            f.name for f in dataclasses.fields(BiwtInput)
        }

    def test_widget_setup_is_named_on_the_factory_instead(self):
        import inspect

        from biwt.gui.walkthrough import create_biwt_widget

        assert "cell_template_paths" in inspect.signature(
            create_biwt_widget
        ).parameters

    def test_snapshot_is_independent_of_the_host_original(self):
        """A run holds a copy, so a host editing its own objects cannot reach it.

        Every mutable field has to be copied, not just the dataclass: a host that
        edits its ``DomainSpec`` in place would otherwise rewrite the domain a
        finished run already reported as ``domain_used``.
        """
        from biwt.types import DomainSpec

        original = BiwtInput(
            preferred_domain=DomainSpec(xmin=-1, xmax=1, ymin=-1, ymax=1),
            host_cell_type_names=["tumor"],
        )
        frozen = original.snapshot()

        original.preferred_domain.xmax = 999
        original.host_cell_type_names.append("macrophage")

        assert frozen.preferred_domain.xmax == 1
        assert frozen.host_cell_type_names == ["tumor"]

    def test_the_name_matching_hook_is_widget_setup(self):
        """Behavior, not state: nothing about it changes between runs."""
        import inspect

        from biwt.gui.walkthrough import create_biwt_widget

        fields = {f.name for f in dataclasses.fields(BiwtInput)}
        assert not fields & {"name_matches", "name_match_cutoff", "host_name"}

        params = inspect.signature(create_biwt_widget).parameters
        assert {"name_matches", "name_match_cutoff", "host_name"} <= set(params)
        assert params["name_matches"].default is None
        assert params["name_match_cutoff"].default == 0.85

    def test_the_matcher_defaults_to_biwts_own(self):
        from biwt.core.cell_types import resolve_name_matcher

        matcher = resolve_name_matcher()
        assert matcher("Tumor", "tumour")
        assert not matcher("M1 Macrophage", "M2 Macrophage")

    def test_the_matcher_honors_the_host_predicate(self):
        from biwt.core.cell_types import resolve_name_matcher

        assert resolve_name_matcher(lambda a, b: True)("M1 Mac", "M2 Mac")

    def test_the_matcher_honors_the_cutoff(self):
        from biwt.core.cell_types import resolve_name_matcher

        assert not resolve_name_matcher(cutoff=0.99)("Tumor", "tumour")

    def test_the_widget_resolves_it_once_and_keeps_it(self, make_widget):
        """Settled at construction: nothing per-run can make two rows disagree."""
        w, _ = make_widget(name_matches=lambda a, b: True)
        assert w.name_matcher("M1 Macrophage", "M2 Macrophage")
        assert not hasattr(w.session, "name_matcher")


# ---------------------------------------------------------------------------
# apply_rename is re-run on every Continue from the rename step
# ---------------------------------------------------------------------------

class TestApplyRenameIsIdempotent:
    """Re-running apply_rename must not consume its own output.

    The rename window calls it on every Continue, including a Back with nothing
    changed.  It used to rewrite ``cell_prob_feature_dicts`` in place: pass two
    then found no original names left (dropping every cell) and re-zipped the
    already-filtered dicts against the full coordinate array, silently pairing
    probability profiles with the wrong spots.
    """

    def _deconv_session(self, mapping_extra=None):
        s = _session(SPOT_DECONV_CSV)
        s.perform_spot_deconvolution = True
        s.reseed_derived_state()
        s.cell_type_dict_on_edit = {ct: ct for ct in s.cell_types_list_original}
        if mapping_extra:
            s.cell_type_dict_on_edit.update(mapping_extra)
        s.compute_intermediate_types()
        s.cell_types_list_final = [
            mapping_extra.get(ct, ct) if mapping_extra else ct
            for ct in s.intermediate_types
        ]
        s.cell_type_dict_on_rename = {
            ct: (mapping_extra or {}).get(ct, ct)
            for ct in s.cell_types_list_original
        }
        return s

    def test_second_pass_matches_the_first(self):
        s = self._deconv_session({"T_cell": "Tcell"})
        s.apply_rename()
        first_types = list(s.cell_types_final)
        first_dicts = [dict(d) for d in s.cell_prob_feature_dicts_final]
        first_coords = s.spatial_data_final.copy()

        s.apply_rename()
        assert s.cell_types_final == first_types
        assert [dict(d) for d in s.cell_prob_feature_dicts_final] == first_dicts
        assert np.array_equal(s.spatial_data_final, first_coords)

    def test_source_dicts_are_never_mutated(self):
        s = self._deconv_session({"T_cell": "Tcell"})
        before = [dict(d) for d in s.cell_prob_feature_dicts]
        s.apply_rename()
        assert [dict(d) for d in s.cell_prob_feature_dicts] == before

    def test_a_spot_whose_whole_mass_was_deleted_drops_with_its_coordinate(self):
        """Not about deleting every cell type — about one *spot* losing all of its.

        Delete Macrophage and a spot that was pure Macrophage weighs nothing. It
        has to leave, and its coordinate has to leave with it: if the two appends
        ever fall out of step, every spot after the first dropped one is paired
        with a neighbour's location and the placement is silently wrong.

        The fixture keeps mass in every spot, so nothing here is filtered unless
        the profiles are built by hand.
        """
        s = self._deconv_session()
        s.cell_prob_feature_dicts = [
            {"Macrophage": 0.0, "T_cell": 1.0, "Tumor": 0.0},   # survives
            {"Macrophage": 1.0, "T_cell": 0.0, "Tumor": 0.0},   # all mass deleted
            {"Macrophage": 0.5, "T_cell": 0.0, "Tumor": 0.5},   # survives, reduced
        ]
        s.spatial_data = np.array([[10.0, 10.0, 0.0],
                                   [20.0, 20.0, 0.0],
                                   [30.0, 30.0, 0.0]])
        s.cell_type_dict_on_rename = {"T_cell": "T_cell", "Tumor": "Tumor"}

        s.apply_rename()

        assert s.cell_prob_feature_dicts_final == [
            {"T_cell": 1.0, "Tumor": 0.0},
            {"T_cell": 0.0, "Tumor": 0.5},
        ]
        # The first and third rows, in order — the middle one is gone.
        assert s.spatial_data_final.tolist() == [[10.0, 10.0, 0.0],
                                                [30.0, 30.0, 0.0]]
        assert s.cell_types_final == ["T_cell", "Tumor"]

    def test_probabilities_stay_aligned_with_coordinates(self):
        # Deleting a type drops any spot whose probability mass was all in it,
        # which is what used to desynchronize the two arrays on a second pass.
        s = self._deconv_session()
        s.cell_type_dict_on_edit["Macrophage"] = None
        s.compute_intermediate_types()
        s.cell_types_list_final = list(s.intermediate_types)
        s.cell_type_dict_on_rename = {
            ct: ct for ct in s.cell_types_list_original if ct != "Macrophage"
        }
        s.apply_rename()
        s.apply_rename()
        assert len(s.cell_prob_feature_dicts_final) == s.spatial_data_final.shape[0]
        assert all(d for d in s.cell_prob_feature_dicts_final)


# ---------------------------------------------------------------------------
# cell_type_map — the audit trail the host is promised
# ---------------------------------------------------------------------------

class TestResolvedCellTypeMap:
    """The audit trail from every original data label to its final name."""

    def _session_with_edits(self):
        s = _session(NONSPATIAL_CSV)          # Macrophage, T_cell, Tumor
        s.current_column = "type"
        s.collect_cell_type_data()
        s.spatial_query_answer = False
        # Merge Macrophage into Tumor, delete T_cell.
        s.cell_type_dict_on_edit = {
            "Tumor": "Tumor", "Macrophage": "Tumor", "T_cell": None,
        }
        s.compute_intermediate_types()
        s.cell_types_list_final = ["tumor"]
        s.cell_type_dict_on_rename = {"Tumor": "tumor", "Macrophage": "tumor"}
        return s

    def test_merged_originals_both_map_to_the_final_name(self):
        s = self._session_with_edits()
        got = s.resolved_cell_type_map()
        assert got["Tumor"] == "tumor"
        assert got["Macrophage"] == "tumor"

    def test_a_deleted_type_maps_to_none(self):
        s = self._session_with_edits()
        assert s.resolved_cell_type_map()["T_cell"] is None

    def test_every_original_label_appears(self):
        s = self._session_with_edits()
        assert set(s.resolved_cell_type_map()) == set(s.cell_types_list_original)

    def test_an_identity_run_maps_each_type_to_itself(self):
        s = _session(NONSPATIAL_CSV)
        s.current_column = "type"
        s.collect_cell_type_data()
        s.cell_type_dict_on_edit = {ct: ct for ct in s.cell_types_list_original}
        s.compute_intermediate_types()
        s.cell_types_list_final = list(s.intermediate_types)
        s.cell_type_dict_on_rename = {ct: ct for ct in s.cell_types_list_original}
        assert s.resolved_cell_type_map() == {ct: ct for ct in s.cell_types_list_original}

    def test_before_the_rename_step_nothing_is_resolved_yet(self):
        s = _session(NONSPATIAL_CSV)
        s.current_column = "type"
        s.collect_cell_type_data()
        assert set(s.resolved_cell_type_map().values()) == {None}


class TestCellTypeOrdering:
    """Cell-type lists are displayed, so they sort case-insensitively."""

    def test_lowercase_initial_names_are_not_filed_last(self):
        s = _session(NONSPATIAL_CSV)
        s.data.obs["type"] = ["myCAF", "Stellate", "iCAF", "B cell", "iCAF", "myCAF"]
        s.current_column = "type"
        s.collect_cell_type_data()
        assert s.cell_types_list_original == ["B cell", "iCAF", "myCAF", "Stellate"]

    def test_intermediate_types_follow_the_same_order(self):
        s = _session(NONSPATIAL_CSV)
        s.cell_type_dict_on_edit = {"Stellate": "Stellate", "iCAF": "iCAF", "myCAF": "myCAF"}
        s.compute_intermediate_types()
        assert s.intermediate_types == ["iCAF", "myCAF", "Stellate"]


# ---------------------------------------------------------------------------
# Format availability — so a host can say what it can read before the user picks
# ---------------------------------------------------------------------------

class TestSupportedFormats:
    def test_every_extension_load_accepts_is_listed(self):
        listed = {ext for fmt in supported_formats() for ext in fmt.extensions}
        assert listed == {".h5ad", ".rds", ".rda", ".rdata", ".csv"}

    def test_csv_needs_nothing_optional(self):
        csv = next(f for f in supported_formats() if ".csv" in f.extensions)
        assert csv.requires == ()
        assert csv.available
        assert csv.hint == ""

    def test_a_missing_requirement_is_reported_with_its_extra(self):
        fmt = FormatSupport(
            extensions=(".zzz",), description="nonsense",
            requires=("definitely_not_installed",), extra="biwt[nonsense]",
        )
        assert not fmt.available
        assert fmt.missing == ("definitely_not_installed",)
        assert "definitely_not_installed" in fmt.hint
        assert "pip install biwt[nonsense]" in fmt.hint

    def test_availability_does_not_import_the_dependency(self, monkeypatch):
        # find_spec, not import: asking must stay cheap and side-effect free.
        import sys
        before = set(sys.modules)
        [f.available for f in supported_formats()]
        assert not (set(sys.modules) - before) & {"anndata", "rpy2", "anndata2ri"}

    def test_a_dependency_whose_parent_is_absent_counts_as_missing(self):
        fmt = FormatSupport(extensions=(".zzz",), description="x",
                            requires=("no_such_pkg.submodule",))
        assert not fmt.available          # find_spec raises here; must not escape

    def test_label_lists_the_extensions(self):
        r = next(f for f in supported_formats() if ".rds" in f.extensions)
        assert r.label == ".rds .rda .rdata"


class TestUsableDomain:
    """A host's domain arrives unchecked, and a degenerate one is fatal later.

    Zero width divides by zero at the counts step; NaN/inf reaches matplotlib.
    Both are raised from a Qt slot, which PyQt5 turns into a process abort — so
    they are repaired at the boundary instead.
    """

    @staticmethod
    def _domain(**kwargs):
        bounds = dict(xmin=-500, xmax=500, ymin=-500, ymax=500)
        bounds.update(kwargs)
        return BiwtInput(preferred_domain=DomainSpec(**bounds)).preferred_domain

    def test_a_usable_domain_is_left_alone(self):
        d = self._domain()
        assert (d.xmin, d.xmax, d.source) == (-500, 500, DomainSource.HOST)

    @pytest.mark.parametrize("bad", [
        {"xmin": 0, "xmax": 0},                     # flat x
        {"ymin": 7, "ymax": 7},                     # flat y
        {"xmax": float("nan")},
        {"ymin": float("-inf")},
    ])
    def test_an_unusable_domain_is_replaced_and_says_so(self, bad):
        d = self._domain(**bad)
        assert (d.xmin, d.xmax) == (-500.0, 500.0)
        # DEFAULT, not HOST: nobody supplied a usable one, and that is also what
        # stops the positions step raising a mismatch against a box never real.
        assert d.source == DomainSource.DEFAULT

    def test_inverted_bounds_are_swapped_rather_than_discarded(self):
        # The intent is unambiguous, and left alone it stacks every cell on one line.
        d = self._domain(xmin=500, xmax=-500)
        assert (d.xmin, d.xmax) == (-500.0, 500.0)
        assert d.source == DomainSource.HOST

    def test_a_flat_z_is_legitimate(self):
        # A 2-D host domain; only x and y feed the divisor.
        d = self._domain(zmin=0, zmax=0)
        assert (d.zmin, d.zmax) == (0, 0)
        assert d.source == DomainSource.HOST

    def test_the_repair_survives_a_snapshot(self):
        # replace() re-runs __post_init__, so a host mutating its own input after
        # construction is normalized too.
        bi = BiwtInput()
        bi.preferred_domain = DomainSpec(xmin=0, xmax=0, ymin=-1, ymax=1)
        assert bi.snapshot().preferred_domain.source == DomainSource.DEFAULT


class TestSingleValueFields:
    """A bare string is one entry, not a list of its characters."""

    def test_a_string_of_names_becomes_one_name(self):
        assert BiwtInput(host_cell_type_names="Tumor").host_cell_type_names == ["Tumor"]


class TestTemplatePathNormalization:
    """`core.templates.normalize_template_paths` — the one repair point.

    These paths reach `os.path.abspath` from a Qt slot, where a raise aborts the
    host process, so what is not a path has to be dropped before it gets there.
    """

    def test_a_bare_string_is_one_path(self):
        """`list("some/path.toml")` would otherwise be one bad path per letter."""
        from biwt.core.templates import normalize_template_paths

        assert normalize_template_paths("a.toml") == [os.path.abspath("a.toml")]

    def test_a_pathlib_path_is_kept_as_its_string(self):
        from pathlib import Path

        from biwt.core.templates import normalize_template_paths

        assert normalize_template_paths([Path("/a/b.toml")]) == ["/a/b.toml"]

    def test_what_is_not_a_path_is_dropped(self):
        from biwt.core.templates import normalize_template_paths

        assert normalize_template_paths(["/a.toml", None, 3, "", "   "]) == ["/a.toml"]

    def test_paths_are_absolute_and_deduped_in_order(self):
        from biwt.core.templates import normalize_template_paths

        assert normalize_template_paths(
            ["/b.toml", "  /a.toml  ", "/b.toml"]
        ) == ["/b.toml", "/a.toml"]


class TestEveryTypeDeletedSpatially:
    def test_apply_rename_survives_an_empty_selection(self):
        """Deleting every cell type left nothing to stack, and np.vstack([])
        raises — from a Qt slot, which takes the host process with it."""
        s = _session(SPATIAL_CSV)
        s.current_column = "type"
        s.collect_cell_type_data()
        s.spatial_query_answer = True
        s.setup_spatial_data()
        s.cell_type_dict_on_edit = {ct: None for ct in s.cell_types_list_original}
        s.compute_intermediate_types()
        s.cell_types_list_final = []
        s.cell_type_dict_on_rename = {}
        s.apply_rename()

        assert s.cell_types_final == []
        assert s.spatial_data_final.shape[0] == 0
        assert s.cell_counts == {}


class TestNoObsColumns:
    def test_a_file_with_no_obs_columns_is_refused_at_load(self, tmp_path):
        """Nothing to pick a cell-type column from: the step would show an empty
        dropdown and the next one would read None."""
        anndata = pytest.importorskip("anndata")
        import numpy as np
        import pandas as pd

        path = tmp_path / "bare.h5ad"
        anndata.AnnData(X=np.zeros((3, 2)), obs=pd.DataFrame(index=list("abc"))).write_h5ad(path)

        with pytest.raises(LoadError, match="no obs columns"):
            data_loader.load(str(path))
